feat: add live videos section in epk page (fixes #47)
taleeus/benthos-v2 pull request #48
Opened 2023-01-29 16:41 UTC by amaliacicala

#47

2023-01-29 16:56 UTC, taleeus requested changes

2023-01-29 16:56 UTC, taleeus commented on src/views/Epk.vue
> +    <Section
La sezione mi piace, ma non mettiamo un titolo (tipo Live)? Da cellulare senza titolo fa un po' strano

2023-01-29 22:10 UTC, amaliacicala reviewed
fixed

2023-01-30 07:26 UTC, taleeus approved these changes

2023-01-30 07:26 UTC, merged